schema_version = "1.0.0"
id = "meshy_importer_for_blender_unity"
version = "1.2.0"
name = "Meshy Importer for Blender & Unity"
tagline = "Import Meshy .meshy model files directly into Blender"
maintainer = "FISHHWB"
type = "add-on"
blender_version_min = "4.2.0"
website = "https://github.com/dedzedofficial/Meshy-Importer-for-Blender-Unity"
tags = ["Import-Export"]
license = ["SPDX:MIT"]
